import type { MasterProfile } from "./types";

export const masterRoster: MasterProfile[] = [
  {
    id: "buffett",
    skillSlug: "warren-buffett",
    name: "沃伦·巴菲特",
    en: "Warren Buffett",
    school: "优质价值",
    quote: "价格是你付出的，价值是你得到的。",
    riskBias: "conservative",
    publicDescription: "强调护城河、现金流、管理层与长期复利。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/warren-buffett",
  },
  {
    id: "munger",
    skillSlug: "charlie-munger",
    name: "查理·芒格",
    en: "Charlie Munger",
    school: "多元思维",
    quote: "反过来想，总是反过来想。",
    riskBias: "conservative",
    publicDescription: "先排除愚蠢，再寻找聪明，偏爱逆向检查清单。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/charlie-munger",
  },
  {
    id: "lynch",
    skillSlug: "peter-lynch",
    name: "彼得·林奇",
    en: "Peter Lynch",
    school: "成长价值",
    quote: "投资你真正理解的事物。",
    riskBias: "balanced",
    publicDescription: "从产品、用户和增长感知切入，再回到财务与估值。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/peter-lynch",
  },
  {
    id: "graham",
    skillSlug: "ben-graham",
    name: "本杰明·格雷厄姆",
    en: "Ben Graham",
    school: "深度价值",
    quote: "安全边际是投资的核心原则。",
    riskBias: "conservative",
    publicDescription: "关注折价、资产保护和防御式仓位。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/ben-graham",
  },
  {
    id: "fisher",
    skillSlug: "phil-fisher",
    name: "菲利普·费雪",
    en: "Phil Fisher",
    school: "高质量成长",
    quote: "买最优秀的企业，然后长期持有。",
    riskBias: "balanced",
    publicDescription: "偏爱高质量成长，关注长期竞争力与管理执行力。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/phil-fisher",
  },
  {
    id: "damodaran",
    skillSlug: "aswath-damodaran",
    name: "阿斯沃斯·达摩达兰",
    en: "Aswath Damodaran",
    school: "叙事估值",
    quote: "先讲故事，再把故事翻译成数字。",
    riskBias: "balanced",
    publicDescription: "从商业叙事出发，推导增长、利润、再投资与估值假设。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/aswath-damodaran",
  },
  {
    id: "taleb",
    skillSlug: "nassim-taleb",
    name: "纳西姆·塔勒布",
    en: "Nassim Taleb",
    school: "反脆弱与尾部风险",
    quote: "先避开脆弱，再寻找上行。",
    riskBias: "conservative",
    publicDescription: "重点检查脆弱性、尾部风险、凸性与激励对齐。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/nassim-taleb",
  },
  {
    id: "druckenmiller",
    skillSlug: "stanley-druckenmiller",
    name: "斯坦利·德鲁肯米勒",
    en: "Stanley Druckenmiller",
    school: "宏观趋势与非对称",
    quote: "要在上行大、下行可控的时候重拳出击。",
    riskBias: "aggressive",
    publicDescription: "寻找宏观拐点、趋势强化与高赔率战术仓位。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/stanley-druckenmiller",
  },
  {
    id: "burry",
    skillSlug: "michael-burry",
    name: "迈克尔·伯里",
    en: "Michael Burry",
    school: "逆向与危机观察",
    quote: "市场常常低估结构性风险。",
    riskBias: "balanced",
    publicDescription: "擅长找被忽略的失衡、泡沫与错误定价。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/michael-burry",
  },
  {
    id: "ackman",
    skillSlug: "bill-ackman",
    name: "比尔·阿克曼",
    en: "Bill Ackman",
    school: "高集中度激进投资",
    quote: "高置信度时可以更集中，但必须有清晰催化剂。",
    riskBias: "aggressive",
    publicDescription: "偏好高置信度集中下注，要求催化剂和管理改进路径。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/bill-ackman",
  },
  {
    id: "wood",
    skillSlug: "cathie-wood",
    name: "凯茜·伍德",
    en: "Cathie Wood",
    school: "颠覆式创新",
    quote: "创新会在长期重塑估值体系。",
    riskBias: "aggressive",
    publicDescription: "偏好技术拐点、平台型创新和长周期增长想象力。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/cathie-wood",
  },
  {
    id: "pabrai",
    skillSlug: "mohnish-pabrai",
    name: "莫尼什·帕伯莱",
    en: "Mohnish Pabrai",
    school: "低风险高不对称",
    quote: "Heads I win, tails I don’t lose much.",
    riskBias: "balanced",
    publicDescription: "寻找低下行、高上行的复制型机会。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/mohnish-pabrai",
  },
  {
    id: "jhunjhunwala",
    skillSlug: "rakesh-jhunjhunwala",
    name: "拉凯什·詹金华拉",
    en: "Rakesh Jhunjhunwala",
    school: "高信念成长",
    quote: "在你有信念时让利润奔跑。",
    riskBias: "aggressive",
    publicDescription: "强调高信念成长、周期识别和让正确仓位跑出来。",
    sourceUrl: "https://github.com/monarchjuno/vibe-investing/tree/main/skills/investor-personas/rakesh-jhunjhunwala",
  },
];

export const masterMap = new Map(masterRoster.map((master) => [master.id, master]));
